server:
    port: 8761

eureka:
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 30 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
        lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8763/eureka/

spring:
    application:
        name: eurka-server